#Lets make a cake
import time
print("           _|_      ")
print("           | |      ")
print("           | |      ")
print("           | |      ")
time.sleep(0.50)
print("     _______________")
print("     |_____________|")
print("     |             |")
print("     |             |")
print("     |             |")
time.sleep(0.25)
print(" ------------------------")
time.sleep(0.50)
print(" |        HAPPY         |")
print(" |      BIRTHDAY        |")
print(" |                      |")
print(" |                      |")
time.sleep(0.50)
print("===========================")
print("|/////////////////////////|")
print("===========================")